site_name: Junjie Zhou
site_url: https://junjiezhou.github.io/Blogs/
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: lime
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
  - tags
 